# Generated by Django 5.1.5 on 2025-01-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic_updated_by_topic_updated_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_dt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created_dt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
    ]
